name: Unit Tests and Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [16.x, 18.x] # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: hardhat
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install

    - run: npx hardhat test
    - run: npx hardhat coverage
    - run: npx istanbul check-coverage --lines 80
    - uses: codecov/codecov-action@v3
      # with:
      #   fail_ci_if_error: true
